### ISSUE TITLE
Fix Progress bar

### ISSUE THREAD

**Issue by twentysixmoons** [open-austin/permit-server#28]
<img width="1106" alt="screen shot 2016-06-05 at 11 02 53 am" src="https://cloud.githubusercontent.com/assets/10767430/15806640/5d015fc2-2b0d-11e6-875b-f010b5a14afd.png">

The progress bar needs to adjust to what sections people are on
- start
- permit eligibility
- prereqs
- Results

**Comment by prestonp** [comment]
since we've removed the progress bar, i'm gonna go head and close this bad boy
