### ISSUE TITLE
Deploy Latest push to Heroku

### ISSUE THREAD

**Issue by twentysixmoons** [open-austin/permit-server#31]
Hey @daniellillja I added a banner per Julia's request so people don't get confused/frustrated if they end up on this page. Can you push it to Heroku? We got featured in a few places so the sooner the better. :)

We should also look into adding people that can deploy. I talked to Julia and intend to keep this project going. More info [here](https://github.com/open-austin/project-ideas/issues/68).

**Comment by daniellillja** [comment]
Deployed :+1:. The Heroku account is actually running under Preston's account so I may not be able to add other users, but I don't mind deploying either.
