### ISSUE TITLE
Back button on Commercial/ Residential page

### ISSUE THREAD

**Issue by twentysixmoons** [open-austin/permit-server#34]
When you click "commercial" you should also be able to go back
<img width="996" alt="screen shot 2016-06-25 at 10 14 48 am" src="https://cloud.githubusercontent.com/assets/10767430/16357488/ad1826c0-3abd-11e6-85d6-98a95c13843b.png">

**Comment by vmacdougal** [comment]
I'm going to fork and work on this.

**Comment by vmacdougal** [comment]
Pull request is up at https://github.com/open-austin/permit-server/pull/36.

**Comment by twentysixmoons** [comment]
Solid!
